### ISSUE TITLE
Большие файлы ломают бота

### ISSUE THREAD

**Issue by dyakovri** [profcomff/print-tgbot#5]
Если отправить файл >3Mb, то бот скажет, что внутри что-то сломалось

```
2023-01-12 20:35:18 - root - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1063, in process_update
    await coroutine
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/handlers.py", line 206, in handler_print
    await update.callback_query.edit_message_text(text=ans['print_err'],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'edit_message_text'
```

**Comment by dyakovri** [comment]
Стоит добавить проверки на status code in range(200,300)

**Comment by Annndruha** [comment]
> Стоит добавить проверки на status code in range(200,300)

Имеешь в виду что API может возвращать не 200, но при этом быть валидным?

**Comment by Annndruha** [comment]
Исправлено в релизе v1.1.0
